server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
  health:
    mongo:
      enabled: true
nhais:
  amqp:
    brokers: ${NHAIS_AMQP_BROKERS:amqp://localhost:5672}
    meshOutboundQueueName: ${NHAIS_MESH_OUTBOUND_QUEUE_NAME:nhais_mesh_outbound}
    meshInboundQueueName: ${NHAIS_MESH_INBOUND_QUEUE_NAME:nhais_mesh_inbound}
    gpSystemInboundQueueName: ${NHAIS_GP_SYSTEM_INBOUND_QUEUE_NAME:nahis_gp_system_inbound}
    exchange: amq.direct
    username: ${NHAIS_AMQP_USERNAME:}
    password: ${NHAIS_AMQP_PASSWORD:}
    maxAttempts: ${NHAIS_AMQP_MAX_RETRIES:3}
    backOffPeriod: ${NHAIS_AMQP_RETRY_DELAY:100}
  mongodb:
    uri: ${NHAIS_MONGO_URI:mongodb://localhost:27017}
    database: ${NHAIS_MONGO_DATABASE_NAME:nhais}
    host: ${NHAIS_MONGO_HOST:}
    port: ${NHAIS_MONGO_PORT:}
    username: ${NHAIS_MONGO_USERNAME:}
    password: ${NHAIS_MONGO_PASSWORD:}
    options: ${NHAIS_MONGO_OPTIONS:}
    autoIndexCreation: ${NHAIS_MONGO_AUTO_INDEX_CREATION:true}